name: counterfactualms
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - absl-py
  - aiohttp
  - alabaster
  - apipkg
  - argon2-cffi
  - async-timeout
  - async_generator
  - attrs
  - babel
  - backports
  - backports.functools_lru_cache
  - blas
  - bleach
  - blinker
  - brotlipy
  - c-ares
  - ca-certificates
  - cachetools
  - certifi
  - cffi
  - chardet
  - click
  - cloudpickle
  - coverage
  - cryptography
  - cudatoolkit=10.1
  - cycler
  - cytoolz
  - dataclasses
  - dask-core
  - decorator
  - defusedxml
  - docutils
  - entrypoints
  - execnet
  - flake8
  - freetype
  - fsspec
  - future
  - google-auth
  - google-auth-oauthlib
  - grpcio
  - idna
  - imageio
  - imagesize
  - importlib-metadata
  - importlib_metadata
  - iniconfig
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isort
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - kiwisolver
  - lcms2
  - libcxx
  - libedit
  - libffi
  - libgfortran
  - libpng
  - libprotobuf
  - libsodium
  - libtiff
  - libuv
  - llvm-openmp
  - lz4-c
  - markdown
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mccabe
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - more-itertools
  - multidict
  - nbclient
  - nbconvert
  - nbformat
  - nbsphinx
  - nbstripout
  - nbval
  - ncurses
  - nest-asyncio
  - networkx
  - ninja
  - notebook
  - numpy
  - numpy-base
  - oauthlib
  - olefile
  - openssl
  - opt_einsum
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pluggy
  - prettytable
  - prometheus_client
  - prompt_toolkit
  - protobuf
  - ptyprocess
  - py
  - py-cpuinfo
  - pyasn1
  - pyasn1-modules
  - pycodestyle
  - pycparser
  - pyflakes
  - pygments
  - pyjwt
  - pyopenssl
  - pypandoc
  - pyparsing
  - pyrsistent
  - pysocks
  - pytest
  - pytest-benchmark
  - pytest-cov
  - pytest-forked
  - pytest-xdist
  - python
  - python-dateutil
  - python_abi
  - pytorch
  - pytorch-lightning
  - pytz
  - pywavelets
  - pyyaml
  - pyzmq
  - readline
  - requests
  - requests-oauthlib
  - rsa
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - simplegeneric
  - six
  - snakeviz
  - snowballstemmer
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sqlite
  - tensorboard
  - tensorboard-plugin-wit
  - terminado
  - testpath
  - threadpoolctl
  - tifffile
  - tk
  - toml
  - toolz
  - torchaudio
  - torchfile
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - urllib3
  - visdom
  - wcwidth
  - webencodings
  - websocket-client
  - werkzeug
  - wheel
  - widgetsnbextension
  - xz
  - yaml
  - yapf
  - yarl
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - pyro-api
    - pyro-ppl
